### ISSUE TITLE
Setting Flags for monorepo projects

### ISSUE THREAD

**Issue by dannyrb** [codecov/codecov-node#140]
I have a `Lerna` Monorepo setup where I have packages in two folders:

- `root/platform/project-name/`
- `root/extensions/project-name/`

## Upload All Reports From Root

I first tried using Jest's multiproject runner, and then rely on `.codecov.yml` to properly split the one coverage report. Each project generates it's coverage report, then the parent project runs `codecov`:

```
overage:
  status:
    project:
      default:
        threshold: 0.10%
      core:
        flags: core
      ui:
        flags: ui
      cornerstone:
        flags: cornerstone
    patch: off
flags:
  core:
    paths:
      - platform/core/src
  ui:
    paths:
      - platform/ui/src
  cornerstone:
    paths:
      - extensions/cornerstone/src
```

I see the following output in CI:

```
lerna success - ohif-core
lerna success - @ohif/i18n
lerna success - react-viewerbase
lerna success - ohif-viewer
  _____          _  
 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v3.5.0
==> Detecting CI Provider
    Circle CI Detected
==> Configuration: 
    Endpoint: https://codecov.io
{ commit: '3acea218fbc52e1f6fc010ff8ef501e4444cb57b',
  branch: 'pull/629',
  package: 'node-v3.5.0' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find /home/circleci/repo -type f -name '*.gcno'  -exec gcov  {} +
==> Scanning for reports
    + /home/circleci/repo/platform/core/coverage/lcov.info
    + /home/circleci/repo/platform/core/coverage/clover.xml
    + /home/circleci/repo/platform/viewer/coverage/lcov.info
    + /home/circleci/repo/platform/viewer/coverage/clover.xml
    + /home/circleci/repo/platform/ui/coverage/lcov.info
    + /home/circleci/repo/platform/ui/coverage/clover.xml
==> Uploading reports
    Success!
    View report at: https://codecov.io/github/OHIF/Viewers/commit/3acea218fbc52e1f6fc010ff8ef501e4444cb57b
```

The GitHub reporter shows each project, but assumes the coverage report applies entirely to each project.

## Upload Reports Individually

After running into issues with the above, I modified each project to upload it's report individually, and to specify it's flag/

Run once, for each project:

`jest --ci --runInBand --collectCoverage && codecov --flags=someflag`

CI reports the files as having been uploaded, but codecov shows an error/issue in the dashboard.

> There was an error processing coverage reports.

**Comment by drazisil** [comment]
Hi @dannyrb 

Can you share the URL on Codecov with the flags that is throwing an error?

**Comment by dannyrb** [comment]
@drazisil, I'm not sure it's picking up my flags to begin with, but here is an example URL:

https://codecov.io/github/OHIF/Viewers/commit/37f60ba0af86e64fc1c00b91cfddb4f616cd0e7a

![image](https://user-images.githubusercontent.com/5797588/61558677-afbe8c80-aa35-11e9-8c0d-a2adfdc6fd06.png)

This example was created by having 3 projects run:

`jest --ci --runInBand --collectCoverage && codecov --flags=someflag`

Where the flags were `core`, `ui`, and `viewer` (one per project).
Because `codecov` was run once per project directory, it shows the correct files being found.
I think in this instance they do not use the `.codecov.yml` located at root.

Any/all guidance is appreciated.

**Comment by dannyrb** [comment]
Other setups I intend to try:

*Maybe .codecov.yaml needs to be accessible for each `codecov` call:*

- Run `jest` and collect coverage per project
- From root, call `codecov` per project with flags & file location

*Maybe specifying flags when already declared by path in .codecov.yaml causes issues:*

- Run `jest` and collect coverage per project
- From root, call `codecov` per project with file location and WITHOUT flag
 
*Maybe past `codecov` calls/uploads are causing issues:*

- Call `codecov` with clear option at the beginning of each build

**Comment by drazisil** [comment]
Hi @dannyrb 

Here's the raw report. https://codecov.io/codecov/v4/raw/2019-07-19/EDD2C6D0C6494F5E2BCE227FBF32CFF7/37f60ba0af86e64fc1c00b91cfddb4f616cd0e7a/55078135-8355-45b1-9c22-cb319a16d731.txt

There's an issue with path mapping,

`/home/circleci/repo/platform/viewer/src/WhiteLabellingContext.js` vs `src/WhiteLabellingContext.js` so Codecov can't match the coverage to the source.

You can read how to add this mapping to your `codecov.yml` file here: https://docs.codecov.io/docs/fixing-paths

**Comment by dannyrb** [comment]
@drazisil I spent some time tweaking those values at the `root` `.codecov.yml`, and per project, but to no avail. I'm not sure how to continue testing without a means of seeing the output and how the files are mapped.

I've started trying to solve the problem using Jest's multi-project runner, but my issue then becomes that the entire report applies to all projects, and the flags appear to be ignored. For example:

![image](https://user-images.githubusercontent.com/5797588/62388461-60935400-b52b-11e9-9f1e-d4c6d067e6f6.png)

- https://codecov.io/gh/OHIF/Viewers/compare/5ac9048ef08c7bbab5ff3548343a6a65771d2e34...e4a3510c868b6332d26d5b67f329271616111610

With:

```
coverage:
  status:
    project:
      default:
        threshold: 0.10%
      core:
        flags: core
      viewer:
        flags: viewer
    patch: off
flags:
  core:
    paths:
      - platform/core
  viewer:
    paths:
      - platform/viewer
```
