### ISSUE TITLE
v3.8.0: SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by stewie1570** [codecov/codecov-node#228]
This error (below) started happening in my Travis CI build as of `codecov@3.8.0`. I updated my `.travis.yml` to install `codecov@3.7.2` and that fixed my build.

Here is the console output:
> $ codecov
/home/travis/.nvm/versions/node/v13.6.0/lib/node_modules/codecov/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^
SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1060:16)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v13.6.0/lib/node_modules/codecov/node_modules/teeny-request/build/src/index.js:21:14)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
The command "codecov" exited with 1.

And my `.travis.yml`:
```yml
language: node_js

node_js:
  - '13.6.0'
  
cache: yarn

script:
  - npm install codecov@3.7.2 -g
  - yarn
  - yarn test
  - coveralls < coverage/lcov.info
  - codecov
  - yarn build

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
```

Do I need a later version of Node running in TravisCI?

Here is a link to a failed build: https://travis-ci.org/github/stewie1570/leaf-validator/builds/734434030
