### ISSUE TITLE
Slack notifications are not working - how to debug why?

### ISSUE THREAD

**Issue by ellenaua** [codecov/codecov-node#319]
Hi guys! I added Slack webhook URL to our codecov.yml but Slack notifications are not sent. How can I debug it to understand why?

```
codecov:
  token: "token_here"
coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/some_hash_here"
        only_pulls: false
        threshold: 0%
        branches: null
```
