### ISSUE TITLE
Running into multiple issues with codecov 

### ISSUE THREAD

**Issue by s1mrankaur** [codecov/codecov-node#378]
I feel like I am hitting a wall with codecov. Trying to reach out to community forum and support. Posting the issues here:

This is what my codecov.yml looks like:
```

codecov:
  bot: Simran
  max_report_age: false
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
comment:
  behavior: default
  layout: reach, diff, flags, files
  require_base: false
  require_changes: false
  require_head: true
coverage:
  status:
    project:
      default:
        target: 80.0
        threshold: 1.0
        paths:
          - "services"
          - "resources"
          - "packages"
          - "shared"
          - "lib"
ignore:
  - "common-test-helpers" # ignore folders and all its contents
  - "e2e-tests"
  - "integration-tests"
  - ".devcontainer"
  - "scripts"
  - "*.config.js"

```

Follows the issues I am facing:

1.	PR’s not showing up in Codecov
2.	No PR comments on Bitbucket cloud
3.	Missing coverage report for folders (for ex: services) that weren’t excluded from Codecov reports 

I have tried both with codecov-node and bash uploader.
